// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528195603_fixEntrenamiento2")]
    partial class fixEntrenamiento2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<int>("DniCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdClase")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.HasKey("IdAsistencia");

                    b.ToTable("Asistencia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.Property<int>("IdCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCancha"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoCanchaId")
                        .HasColumnType("int");

                    b.HasKey("IdCancha");

                    b.HasIndex("TipoCanchaId");

                    b.ToTable("Cancha", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.Property<int>("IdClase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClase"));

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date");

                    b.Property<int>("DniProfesor")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("IdActividad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdClase");

                    b.HasIndex("DniProfesor");

                    b.ToTable("Clase", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cobro", b =>
                {
                    b.Property<int>("IdCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCobro"));

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdCobro");

                    b.HasIndex("IdReserva");

                    b.ToTable("Cobro", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Competencia", b =>
                {
                    b.Property<int>("IdCompetencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompetencia"));

                    b.Property<int>("Cupos")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoCompetencia")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("IdCompetencia");

                    b.ToTable("Competencia", (string)null);

                    b.HasDiscriminator<string>("TipoCompetencia").HasValue("Competencia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Descuento", b =>
                {
                    b.Property<int>("IdDescuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDescuento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("IdDescuento");

                    b.ToTable("Descuento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Entrenamiento", b =>
                {
                    b.Property<int>("IdEntrenamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntrenamiento"));

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<int>("DniEntrenador")
                        .HasColumnType("int");

                    b.Property<int?>("EntrenadorDni")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("IdActividad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdEntrenamiento");

                    b.HasIndex("DniEntrenador");

                    b.HasIndex("EntrenadorDni");

                    b.ToTable("Entrenamiento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<int?>("CompetenciaIdCompetencia")
                        .HasColumnType("int");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdCompetencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Victorias")
                        .HasColumnType("int");

                    b.HasKey("IdEquipo");

                    b.HasIndex("CompetenciaIdCompetencia");

                    b.ToTable("Equipo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HorarioCancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCancha");

                    b.ToTable("HorarioCancha", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<int>("DniCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAct")
                        .HasColumnType("int");

                    b.Property<int>("IdDescuento")
                        .HasColumnType("int");

                    b.Property<int>("NroAct")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioInscr")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("claseIdClase")
                        .HasColumnType("int");

                    b.Property<int?>("competenciaIdCompetencia")
                        .HasColumnType("int");

                    b.Property<int?>("entrenamientoIdEntrenamiento")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("DniCliente");

                    b.HasIndex("claseIdClase");

                    b.HasIndex("competenciaIdCompetencia");

                    b.HasIndex("entrenamientoIdEntrenamiento");

                    b.ToTable("Inscripcion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Partido", b =>
                {
                    b.Property<int>("IdPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartido"));

                    b.Property<int?>("EquipoIdEquipo")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCompetencia")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipoLocal")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipoVis")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPartido");

                    b.HasIndex("EquipoIdEquipo");

                    b.HasIndex("IdCompetencia");

                    b.HasIndex("IdEquipoLocal");

                    b.HasIndex("IdEquipoVis");

                    b.ToTable("Partido", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Recibo", b =>
                {
                    b.Property<int>("IdRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecibo"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCobro")
                        .HasColumnType("int");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdRecibo");

                    b.HasIndex("IdCobro");

                    b.HasIndex("IdReserva");

                    b.ToTable("Recibo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdReporte");

                    b.ToTable("Reporte", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<int>("DniCliente")
                        .HasColumnType("int");

                    b.Property<bool>("EsValida")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int");

                    b.Property<int>("IdCanchaHorario")
                        .HasColumnType("int");

                    b.Property<int?>("IdDescuento")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdReserva");

                    b.HasIndex("DniCliente");

                    b.HasIndex("IdCancha");

                    b.HasIndex("IdCanchaHorario");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoCancha", b =>
                {
                    b.Property<int>("IdTipoCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoCancha"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Superficie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoCancha");

                    b.ToTable("TipoCancha", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Dni");

                    b.ToTable("Usuario", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Liga", b =>
                {
                    b.HasBaseType("Domain.Entities.Competencia");

                    b.HasDiscriminator().HasValue("Liga");
                });

            modelBuilder.Entity("Domain.Entities.Torneo", b =>
                {
                    b.HasBaseType("Domain.Entities.Competencia");

                    b.Property<string>("FaseAct")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue("Torneo");
                });

            modelBuilder.Entity("Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("Domain.Entities.Usuario");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.HasBaseType("Domain.Entities.Usuario");

                    b.Property<bool>("EsSocio")
                        .HasColumnType("bit");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Domain.Entities.Profesional", b =>
                {
                    b.HasBaseType("Domain.Entities.Usuario");

                    b.Property<string>("Certificado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaCertificado")
                        .HasColumnType("bit");

                    b.ToTable("Profesional", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Entrenador", b =>
                {
                    b.HasBaseType("Domain.Entities.Profesional");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.HasBaseType("Domain.Entities.Profesional");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.HasOne("Domain.Entities.TipoCancha", "TipoCancha")
                        .WithMany()
                        .HasForeignKey("TipoCanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCancha");
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.HasOne("Domain.Entities.Profesor", "Profesor")
                        .WithMany("Clases")
                        .HasForeignKey("DniProfesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Domain.Entities.Cobro", b =>
                {
                    b.HasOne("Domain.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Domain.Entities.Entrenamiento", b =>
                {
                    b.HasOne("Domain.Entities.Entrenador", "Entrenador")
                        .WithMany()
                        .HasForeignKey("DniEntrenador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Entrenador", null)
                        .WithMany("Entrenamientos")
                        .HasForeignKey("EntrenadorDni");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("Domain.Entities.Equipo", b =>
                {
                    b.HasOne("Domain.Entities.Competencia", null)
                        .WithMany("Equipos")
                        .HasForeignKey("CompetenciaIdCompetencia");
                });

            modelBuilder.Entity("Domain.Entities.HorarioCancha", b =>
                {
                    b.HasOne("Domain.Entities.Cancha", "Cancha")
                        .WithMany("Disponibilidad")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "cliente")
                        .WithMany("Inscripciones")
                        .HasForeignKey("DniCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clase", "clase")
                        .WithMany("Inscripto")
                        .HasForeignKey("claseIdClase");

                    b.HasOne("Domain.Entities.Competencia", "competencia")
                        .WithMany("Inscriptos")
                        .HasForeignKey("competenciaIdCompetencia");

                    b.HasOne("Domain.Entities.Entrenamiento", "entrenamiento")
                        .WithMany("Inscriptos")
                        .HasForeignKey("entrenamientoIdEntrenamiento");

                    b.Navigation("clase");

                    b.Navigation("cliente");

                    b.Navigation("competencia");

                    b.Navigation("entrenamiento");
                });

            modelBuilder.Entity("Domain.Entities.Partido", b =>
                {
                    b.HasOne("Domain.Entities.Equipo", null)
                        .WithMany("Partidos")
                        .HasForeignKey("EquipoIdEquipo");

                    b.HasOne("Domain.Entities.Competencia", "Competencia")
                        .WithMany("Partidos")
                        .HasForeignKey("IdCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("IdEquipoLocal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Equipo", "EquipoVis")
                        .WithMany()
                        .HasForeignKey("IdEquipoVis")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competencia");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVis");
                });

            modelBuilder.Entity("Domain.Entities.Recibo", b =>
                {
                    b.HasOne("Domain.Entities.Cobro", "Cobro")
                        .WithMany()
                        .HasForeignKey("IdCobro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cobro");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("DniCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HorarioCancha", "HorarioCancha")
                        .WithMany()
                        .HasForeignKey("IdCanchaHorario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");

                    b.Navigation("HorarioCancha");
                });

            modelBuilder.Entity("Domain.Entities.Profesional", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Profesional", "Dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Entrenador", b =>
                {
                    b.HasOne("Domain.Entities.Profesional", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Entrenador", "Dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.HasOne("Domain.Entities.Profesional", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Profesor", "Dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Cancha", b =>
                {
                    b.Navigation("Disponibilidad");
                });

            modelBuilder.Entity("Domain.Entities.Clase", b =>
                {
                    b.Navigation("Inscripto");
                });

            modelBuilder.Entity("Domain.Entities.Competencia", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Inscriptos");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Domain.Entities.Entrenamiento", b =>
                {
                    b.Navigation("Inscriptos");
                });

            modelBuilder.Entity("Domain.Entities.Equipo", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Domain.Entities.Entrenador", b =>
                {
                    b.Navigation("Entrenamientos");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Clases");
                });
#pragma warning restore 612, 618
        }
    }
}
